name: Build

on:
  workflow_dispatch:
    inputs:
      CORE:
        description: 'Xray-core Version'
        required: false
        default: ''
      release_tag:
        description: 'Tag Version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22.5'
        cache: false

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        export PATH=$PATH:~/go/bin

    - name: Build
      run: |
         mkdir -p assets data
         bash gen_assets.sh download
         cp -v data/*.dat assets/
         go get github.com/xtls/xray-core@${{ github.event.inputs.CORE }} || true
         gomobile init
         go mod tidy
         gomobile bind -v -androidapi 27 -ldflags='-s -w' ./

    - name: Upload AndroidLibXrayLite to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./libv2ray*r
        tag: ${{ github.event.inputs.release_tag }}
        file_glob: true

    - name: Update library
      run: |
        git config --global user.email jarbull86@gmail.com
        git config --global user.name AnGgIt86
        rm -rfd *.jar && rm -rfd libv2ray*r && rm -rfd data
        git add -f .
        git commit -m "Core Update ${{ github.event.inputs.release_tag }}"
        git push
